### PR TITLE
Slider component

### PR DESCRIPTION
**Pull request by Davwidos**
With slider i added preview with examples of use.
Here is documentation for [embla-carusel](https://www.embla-carousel.com/)

### CODE REVIEW

**Review by JustinNowoczek — APPROVED** [review]
Idk what to do here, as I dont really understand the code, and you used styled components even though we decided on modules. And i dont think you should be showing the examples in the app, since this will be merged together with already working parts of the page. Either way the sliders work i guess.

**Comment by Davwidos** [comment]
@JustinNowoczek I added examples in app only to have easy access to preview in vercel. Before merge i will delete examples in `App.tsx `.  I used styled componets only for dynamicly definig flex-basis for slide with constant number of slides in view. Should i use inline style insted? Can you tell which parts are hard to understend so i can improve/explain them. Also here is documentation for embla-carusel  https://www.embla-carousel.com/

**Comment by danon321** [comment]
image
to mi nie działa

**Comment by JustinNowoczek** [comment]
After your explanation, all of my issues are resolved but the choice of extra library, I dont think we should add an entire other lib for 1 component, so maybe use inline like you said, or just add with the modules

**Review by weswojciech — APPROVED** [review]
Seems good to me, working properly, didn't find any issues

**Pull request merged**
